# Generated by Django 3.0.5 on 2020-05-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subjet',
            new_name='subject',
        ),
    ]
